using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Nino.Generator.Metadata;

namespace Nino.Generator.Common;

public partial class DeserializerGenerator
{
    private void GenerateTrivialCode(SourceProductionContext spc, HashSet<ITypeSymbol> generatedTypes)
    {
        var compilation = Compilation;
        var sb = new StringBuilder();
        sb.GenerateClassDeserializeMethods("string");
        HashSet<string> generatedTypeNames = new();

        foreach (var ninoType in NinoTypes)
        {
            try
            {
                if (!generatedTypes.Add(ninoType.TypeSymbol))
                    continue;
                if (!generatedTypeNames.Add(ninoType.TypeSymbol.GetDisplayString()))
                    continue;

                if (!ninoType.TypeSymbol.IsInstanceType() ||
                    !string.IsNullOrEmpty(ninoType.CustomDeserializer))
                    continue;
                sb.AppendLine();
                GenerateImpl(spc, sb, ninoType, false);
                sb.AppendLine();
                GenerateImpl(spc, sb, ninoType, true);
                sb.AppendLine();
            }
            catch (Exception e)
            {
                sb.AppendLine($"/* Error: {e.Message} for type {ninoType.TypeSymbol.GetTypeFullName()}");
                //add stacktrace
                foreach (var line in e.StackTrace.Split('\n'))
                {
                    sb.AppendLine($" * {line}");
                }

                //end error
                sb.AppendLine(" */");
            }
        }

        var curNamespace = compilation.AssemblyName!.GetNamespace();

        // Collect all custom formatters for static field generation
        var globalCustomFormatters = CollectGlobalCustomFormatters();
        var staticFormatterFields = GenerateStaticFormatterFields(globalCustomFormatters);

        // generate code
        var code = $$"""
                     // <auto-generated/>

                     using System;
                     using global::Nino.Core;
                     using System.Buffers;
                     using System.ComponentModel;
                     using System.Collections.Generic;
                     using System.Collections.Concurrent;
                     using System.Runtime.InteropServices;
                     using System.Runtime.CompilerServices;

                     namespace {{curNamespace}}
                     {
                         public static partial class Deserializer
                         {{{staticFormatterFields}}
                     {{GeneratePrivateDeserializeImplMethodBody("string", "        ")}}
                             
                     {{sb}}    }
                     }
                     """;

        spc.AddSource($"{curNamespace}.Deserializer.g.cs", code);
    }

    private void GenerateImpl(SourceProductionContext spc, StringBuilder sb, NinoType ninoType, bool byRef)
    {
        string decl = byRef ? "ref" : "out";
        string suffix = byRef ? "Ref" : "";

        sb.AppendLine($$"""
                                public static void DeserializeImpl{{suffix}}({{decl}} {{ninoType.TypeSymbol.GetTypeFullName()}} value, ref Reader reader)
                                {
                                #if {{NinoTypeHelper.WeakVersionToleranceSymbol}}
                                   if (reader.Eof)
                                   {
                                      value = default;
                                      return;
                                   }
                                #endif
                        """);

        if (ninoType.IsPolymorphic())
        {
            sb.AppendLine("            reader.Read(out int typeId);");
            sb.AppendLine("            if(typeId == TypeCollector.Null)");
            sb.AppendLine("            {");
            sb.AppendLine("                value = default;");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine(
                $"            else if(typeId != NinoTypeConst.{ninoType.TypeSymbol.GetTypeFullName().GetTypeConstName()})");
            sb.AppendLine("                throw new InvalidOperationException(\"Invalid type id\");");
            sb.AppendLine();
        }


        if (ninoType.TypeSymbol.IsUnmanagedType)
        {
            // Even for unmanaged types, we need version tolerance
            sb.AppendLine($"#if {NinoTypeHelper.WeakVersionToleranceSymbol}");
            sb.AppendLine("            if (!reader.Eof)");
            sb.AppendLine("            {");
            sb.AppendLine("                reader.UnsafeRead(out value);");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine("                value = default;");
            sb.AppendLine("            }");
            sb.AppendLine("#else");
            sb.AppendLine("            reader.UnsafeRead(out value);");
            sb.AppendLine("#endif");
        }
        else
        {
            CreateInstance(spc, sb, ninoType, "value", byRef);
        }

        sb.AppendLine("        }");
    }

    // Helper: Generate read statement based on type kind
    private string GenerateReadStatement(NinoMember member, string tempName,
        Func<ITypeSymbol, string> getDeserializerVar,
        Dictionary<NinoMember, string> customFormatterVars)
    {
        var declaredType = member.Type;

        if (member.HasCustomFormatter())
        {
            // PRIORITY 1: Custom formatter (highest priority)
            if (customFormatterVars.TryGetValue(member, out var formatterVar))
            {
                return $"{formatterVar}.Deserialize(out {tempName}, ref reader);";
            }
        }

        var kind = declaredType.GetKind(NinoGraph, GeneratedBuiltInTypes);

        switch (kind)
        {
            case NinoTypeHelper.NinoTypeKind.Unmanaged:
                // PRIORITY 2: Unmanaged types - direct read
                return $"reader.UnsafeRead(out {tempName});";

            case NinoTypeHelper.NinoTypeKind.Boxed:
                // PRIORITY 3: Object type - use polymorphic deserialization
                return $"{tempName} = NinoDeserializer.DeserializeBoxed(ref reader, null);";

            case NinoTypeHelper.NinoTypeKind.BuiltIn:
                // PRIORITY 4: String types or built-in types
                if (declaredType.SpecialType == SpecialType.System_String)
                {
                    return member.IsUtf8String
                        ? $"reader.ReadUtf8(out {tempName});"
                        : $"reader.Read(out {tempName});";
                }
                else
                {
                    return $"Deserializer.Deserialize(out {tempName}, ref reader);";
                }

            case NinoTypeHelper.NinoTypeKind.NinoType:
                // PRIORITY 5: NinoType - use CachedDeserializer
                var deserializerVar = getDeserializerVar(declaredType);
                return $"{deserializerVar}.Deserialize(out {tempName}, ref reader);";

            default:
                return $"// Unable to deserialize {tempName}";
        }
    }

    // Helper: Generate ref deserialization for public fields
    private void GenerateRefDeserializePublicField(StringBuilder sb, NinoMember member,
        string valName, Func<ITypeSymbol, string> getDeserializerVar,
        Dictionary<NinoMember, string> customFormatterVars)
    {
        var declaredType = member.Type;
        var name = member.Name;

        if (member.HasCustomFormatter())
        {
            // PRIORITY 1: Custom formatter (highest priority)
            if (customFormatterVars.TryGetValue(member, out var formatterVar))
            {
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {formatterVar}.DeserializeRef(ref {valName}.{name}, ref reader);");
                }
                else
                {
                    sb.AppendLine($"            if ({valName}.{name} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.DeserializeRef(ref {valName}.{name}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.Deserialize(out {valName}.{name}, ref reader);");
                    sb.AppendLine("            }");
                }
                return;
            }
        }

        var kind = declaredType.GetKind(NinoGraph, GeneratedBuiltInTypes);

        switch (kind)
        {
            case NinoTypeHelper.NinoTypeKind.Unmanaged:
                sb.AppendLine($"            reader.UnsafeRead(out {valName}.{name});");
                break;

            case NinoTypeHelper.NinoTypeKind.Boxed:
                sb.AppendLine($"            NinoDeserializer.DeserializeRefBoxed(ref {valName}.{name}, ref reader, null);");
                break;

            case NinoTypeHelper.NinoTypeKind.BuiltIn:
                if (declaredType.SpecialType == SpecialType.System_String)
                {
                    if (member.IsUtf8String)
                        sb.AppendLine($"            reader.ReadUtf8(out {valName}.{name});");
                    else
                        sb.AppendLine($"            reader.Read(out {valName}.{name});");
                }
                else
                {
                    sb.AppendLine($"            Deserializer.DeserializeRef(ref {valName}.{name}, ref reader);");
                }
                break;

            case NinoTypeHelper.NinoTypeKind.NinoType:
                var deserializerVar = getDeserializerVar(declaredType);
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {deserializerVar}.DeserializeRef(ref {valName}.{name}, ref reader);");
                }
                else
                {
                    sb.AppendLine($"            if ({valName}.{name} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.DeserializeRef(ref {valName}.{name}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.Deserialize(out {valName}.{name}, ref reader);");
                    sb.AppendLine("            }");
                }
                break;
        }
    }

    // Helper: Generate ref deserialization with temp variable (for properties/private fields)
    private void GenerateRefDeserializeWithTemp(StringBuilder sb, NinoMember member,
        string tempName, Func<ITypeSymbol, string> getDeserializerVar,
        Dictionary<NinoMember, string> customFormatterVars)
    {
        var declaredType = member.Type;

        if (member.HasCustomFormatter())
        {
            if (customFormatterVars.TryGetValue(member, out var formatterVar))
            {
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {formatterVar}.DeserializeRef(ref {tempName}, ref reader);");
                }
                else
                {
                    sb.AppendLine($"            if ({tempName} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.DeserializeRef(ref {tempName}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.Deserialize(out {tempName}, ref reader);");
                    sb.AppendLine("            }");
                }
                return;
            }
        }

        var kind = declaredType.GetKind(NinoGraph, GeneratedBuiltInTypes);

        switch (kind)
        {
            case NinoTypeHelper.NinoTypeKind.Unmanaged:
                sb.AppendLine($"            reader.UnsafeRead(out {tempName});");
                break;

            case NinoTypeHelper.NinoTypeKind.Boxed:
                sb.AppendLine($"            {tempName} = NinoDeserializer.DeserializeBoxed(ref reader, null);");
                break;

            case NinoTypeHelper.NinoTypeKind.BuiltIn:
                if (declaredType.SpecialType == SpecialType.System_String)
                {
                    if (member.IsUtf8String)
                        sb.AppendLine($"            reader.ReadUtf8(out {tempName});");
                    else
                        sb.AppendLine($"            reader.Read(out {tempName});");
                }
                else
                {
                    sb.AppendLine($"            Deserializer.Deserialize(out {tempName}, ref reader);");
                }
                break;

            case NinoTypeHelper.NinoTypeKind.NinoType:
                var deserializerVar = getDeserializerVar(declaredType);
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {deserializerVar}.DeserializeRef(ref {tempName}, ref reader);");
                }
                else
                {
                    sb.AppendLine($"            if ({tempName} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.DeserializeRef(ref {tempName}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.Deserialize(out {tempName}, ref reader);");
                    sb.AppendLine("            }");
                }
                break;
        }
    }

    // Helper: Generate private field access deserialization (NET8.0+)
    private void GeneratePrivateFieldDeserialize(StringBuilder sb, NinoMember member,
        string valName, string name, NinoType nt,
        Func<ITypeSymbol, string> getDeserializerVar,
        Dictionary<NinoMember, string> customFormatterVars)
    {
        var declaredType = member.Type;
        var accessName = nt.TypeSymbol.IsValueType ? $"ref {valName}" : valName;

        if (member.HasCustomFormatter())
        {
            if (customFormatterVars.TryGetValue(member, out var formatterVar))
            {
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {formatterVar}.DeserializeRef(ref PrivateAccessor.__{name}__({accessName}), ref reader);");
                }
                else
                {
                    sb.AppendLine($"            ref var field_{name} = ref PrivateAccessor.__{name}__({accessName});");
                    sb.AppendLine($"            if (field_{name} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.DeserializeRef(ref field_{name}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.Deserialize(out field_{name}, ref reader);");
                    sb.AppendLine("            }");
                }
                return;
            }
        }

        var kind = declaredType.GetKind(NinoGraph, GeneratedBuiltInTypes);

        switch (kind)
        {
            case NinoTypeHelper.NinoTypeKind.Unmanaged:
                sb.AppendLine($"            reader.UnsafeRead(out PrivateAccessor.__{name}__({accessName}));");
                break;

            case NinoTypeHelper.NinoTypeKind.Boxed:
                sb.AppendLine($"            ref var field_{name} = ref PrivateAccessor.__{name}__({accessName});");
                sb.AppendLine($"            NinoDeserializer.DeserializeRefBoxed(ref field_{name}, ref reader, null);");
                break;

            case NinoTypeHelper.NinoTypeKind.BuiltIn:
                if (declaredType.SpecialType == SpecialType.System_String)
                {
                    if (member.IsUtf8String)
                        sb.AppendLine($"            reader.ReadUtf8(out PrivateAccessor.__{name}__({accessName}));");
                    else
                        sb.AppendLine($"            reader.Read(out PrivateAccessor.__{name}__({accessName}));");
                }
                else
                {
                    sb.AppendLine($"            ref var field_{name} = ref PrivateAccessor.__{name}__({accessName});");
                    sb.AppendLine($"            Deserializer.DeserializeRef(ref field_{name}, ref reader);");
                }
                break;

            case NinoTypeHelper.NinoTypeKind.NinoType:
                var deserializerVar = getDeserializerVar(declaredType);
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {deserializerVar}.DeserializeRef(ref PrivateAccessor.__{name}__({accessName}), ref reader);");
                }
                else
                {
                    sb.AppendLine($"            ref var field_{name} = ref PrivateAccessor.__{name}__({accessName});");
                    sb.AppendLine($"            if (field_{name} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.DeserializeRef(ref field_{name}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.Deserialize(out field_{name}, ref reader);");
                    sb.AppendLine("            }");
                }
                break;
        }
    }

    // Helper: Generate private field/property deserialization fallback (< NET8.0)
    private void GeneratePrivateFieldDeserializeFallback(StringBuilder sb, NinoMember member,
        string valName, string name, string tempName,
        Func<ITypeSymbol, string> getDeserializerVar,
        Dictionary<NinoMember, string> customFormatterVars)
    {
        var declaredType = member.Type;

        if (member.HasCustomFormatter())
        {
            if (customFormatterVars.TryGetValue(member, out var formatterVar))
            {
                sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName} = {valName}.__nino__generated__{name};");
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {formatterVar}.DeserializeRef(ref {tempName}, ref reader);");
                }
                else
                {
                    sb.AppendLine($"            if ({tempName} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.DeserializeRef(ref {tempName}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {formatterVar}.Deserialize(out {tempName}, ref reader);");
                    sb.AppendLine("            }");
                }
                sb.AppendLine($"            {valName}.__nino__generated__{name} = {tempName};");
                return;
            }
        }

        var kind = declaredType.GetKind(NinoGraph, GeneratedBuiltInTypes);

        switch (kind)
        {
            case NinoTypeHelper.NinoTypeKind.Unmanaged:
                sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName};");
                sb.AppendLine($"            reader.UnsafeRead(out {tempName});");
                sb.AppendLine($"            {valName}.__nino__generated__{name} = {tempName};");
                break;

            case NinoTypeHelper.NinoTypeKind.Boxed:
                sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName};");
                sb.AppendLine($"            {tempName} = NinoDeserializer.DeserializeBoxed(ref reader, null);");
                sb.AppendLine($"            {valName}.__nino__generated__{name} = {tempName};");
                break;

            case NinoTypeHelper.NinoTypeKind.BuiltIn:
                if (declaredType.SpecialType == SpecialType.System_String)
                {
                    sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName};");
                    if (member.IsUtf8String)
                        sb.AppendLine($"            reader.ReadUtf8(out {tempName});");
                    else
                        sb.AppendLine($"            reader.Read(out {tempName});");
                    sb.AppendLine($"            {valName}.__nino__generated__{name} = {tempName};");
                }
                else
                {
                    sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName} = {valName}.__nino__generated__{name};");
                    sb.AppendLine($"            Deserializer.DeserializeRef(ref {tempName}, ref reader);");
                    sb.AppendLine($"            {valName}.__nino__generated__{name} = {tempName};");
                }
                break;

            case NinoTypeHelper.NinoTypeKind.NinoType:
                sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName} = {valName}.__nino__generated__{name};");
                var deserializerVar = getDeserializerVar(declaredType);
                if (declaredType.IsValueType)
                {
                    sb.AppendLine($"            {deserializerVar}.DeserializeRef(ref {tempName}, ref reader);");
                }
                else
                {
                    sb.AppendLine($"            if ({tempName} != null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.DeserializeRef(ref {tempName}, ref reader);");
                    sb.AppendLine("            }");
                    sb.AppendLine("            else");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                {deserializerVar}.Deserialize(out {tempName}, ref reader);");
                    sb.AppendLine("            }");
                }
                sb.AppendLine($"            {valName}.__nino__generated__{name} = {tempName};");
                break;
        }
    }

    private (List<(string, string)> vars,
        List<(string, string, bool)> privateVars,
        Dictionary<string, string> args,
        Dictionary<string, string> tupleMap) WriteMembers(
            string valName, StringBuilder sb, NinoType nt, string[] constructorMember, bool byRef)
    {
        List<(string, string)> vars = new List<(string, string)>();
        List<(string, string, bool)> privateVars = new List<(string, string, bool)>();
        Dictionary<string, string> args = new Dictionary<string, string>();
        Dictionary<string, string> tupleMap = new Dictionary<string, string>();

        List<string> valNames = new();

        // First pass: collect all types that need deserializers or custom formatters
        HashSet<ITypeSymbol> typesNeedingDeserializers = new(SymbolEqualityComparer.Default);
        HashSet<NinoMember> membersWithCustomFormatters = new();
        List<List<NinoMember>> groups = nt.GroupByPrimitivity().ToList();

        foreach (var memberGroup in groups)
        {
            foreach (var member in memberGroup)
            {
                if (member.IsCtorParameter) continue;

                if (member.HasCustomFormatter())
                {
                    membersWithCustomFormatters.Add(member);
                }
                else
                {
                    var kind = member.Type.GetKind(NinoGraph, GeneratedBuiltInTypes);
                    if (kind == NinoTypeHelper.NinoTypeKind.NinoType)
                    {
                        typesNeedingDeserializers.Add(member.Type);
                    }
                    // Unmanaged, Boxed, and BuiltIn types don't need cached deserializers
                }
            }
        }

        // Generate deserializer declarations for standard types
        Dictionary<string, string> deserializerVarsByType = new();
        foreach (var type in typesNeedingDeserializers)
        {
            var typeDisplayName = type.GetDisplayString();
            var varName = type.GetCachedVariableName("deserializer");

            // Handle potential duplicates by adding a counter
            var originalVarName = varName;
            int counter = 1;
            while (deserializerVarsByType.Values.Contains(varName))
            {
                varName = $"{originalVarName}_{counter}";
                counter++;
            }

            deserializerVarsByType[typeDisplayName] = varName;
            sb.AppendLine($"            var {varName} = CachedDeserializer<{typeDisplayName}>.Instance;");
        }

        // Use static formatter fields instead of local variables
        Dictionary<NinoMember, string> customFormatterVarsByMember = new();
        foreach (var member in membersWithCustomFormatters)
        {
            var formatterType = member.CustomFormatterType();
            if (formatterType != null)
            {
                var varName = formatterType.GetCachedVariableName("formatter");
                customFormatterVarsByMember[member] = varName;
                // Note: Static field should be generated at class level, not as local variable
            }
        }

        // Helper to get deserializer variable name for a type
        string GetDeserializerVarName(ITypeSymbol type)
        {
            var typeDisplayName = type.GetDisplayString();
            if (!deserializerVarsByType.TryGetValue(typeDisplayName, out var varName))
            {
                // Generate the variable name if it wasn't collected earlier (fallback for Priority 4)
                varName = type.GetCachedVariableName("deserializer");
                deserializerVarsByType[typeDisplayName] = varName;
                sb.AppendLine($"            var {varName} = CachedDeserializer<{typeDisplayName}>.Instance;");
            }

            return varName;
        }

        for (var index1 = 0; index1 < groups.Count; index1++)
        {
            var members = groups[index1];
            valNames.Clear();
            foreach (var member in members)
            {
                var name = member.Name;
                var declaredType = member.Type;
                var isCtorParam = member.IsCtorParameter;
                var isPrivate = member.IsPrivate;
                var isProperty = member.IsProperty;

                var t = declaredType.GetDisplayString().Select(c => char.IsLetterOrDigit(c) ? c : '_')
                    .Aggregate("", (a, b) => a + b);
                var tempName = $"{t}_temp_{name}";

                if (constructorMember.Any(c => c.ToLower().Equals(name.ToLower())))
                {
                    args.Add(name, tempName);
                }
                else
                {
                    // we dont want init-only properties from the primary constructor
                    if (!isCtorParam)
                    {
                        if (!isPrivate)
                        {
                            vars.Add((name, tempName));
                        }
                        else
                        {
                            privateVars.Add((name, tempName, isProperty));
                        }
                    }
                }

                valNames.Add(tempName);
            }

            if (members.Count == 1)
            {
                var member = members[0];
                var declaredType = member.Type;

                var tempName = valNames[0];
                //check if the typesymbol declaredType is string
                if (declaredType.SpecialType == SpecialType.System_String)
                {
                    // PRIORITY 3: String types (UTF8 and UTF16 optimizations)
                    var str = member.IsUtf8String
                        ? $"reader.ReadUtf8(out {tempName});"
                        : $"reader.Read(out {tempName});";

                    //weak version tolerance
                    var toleranceCode = $$$"""
                                                       {{{declaredType.GetDisplayString()}}} {{{tempName}}} = default;
                                                       #if {{{NinoTypeHelper.WeakVersionToleranceSymbol}}}
                                                       if (!reader.Eof)
                                                       {
                                                          {{{str}}}
                                                       }
                                                       #else
                                                       {{{str}}}
                                                       #endif
                                           """;

                    sb.AppendLine(toleranceCode);
                    sb.AppendLine();
                }
                else
                {
                    var currentMember = members[0];
                    if (byRef && !currentMember.IsCtorParameter)
                    {
                        vars.Remove((members[0].Name, valNames[0]));
                        privateVars.Remove((members[0].Name, valNames[0], members[0].IsProperty));

                        var isPrivate = currentMember.IsPrivate;
                        var isProperty = currentMember.IsProperty;
                        var name = currentMember.Name;

                        if (!isPrivate && !isProperty)
                        {
                            GenerateRefDeserializePublicField(sb, currentMember, valName, GetDeserializerVarName, customFormatterVarsByMember);
                        }
                        else if (isProperty)
                        {
                            // Properties - store in temp, call ref overload, assign back
                            if (isPrivate)
                            {
                                var accessName = nt.TypeSymbol.IsValueType ? $"ref {valName}" : valName;
                                sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName};");
                                sb.AppendLine("#if NET8_0_OR_GREATER");
                                sb.AppendLine($"            {tempName} = PrivateAccessor.__get__{name}__({accessName});");
                                sb.AppendLine("#else");
                                sb.AppendLine($"            {tempName} = {valName}.__nino__generated__{name};");
                                sb.AppendLine("#endif");
                            }
                            else
                            {
                                sb.AppendLine($"            {declaredType.GetDisplayString()} {tempName} = {valName}.{name};");
                            }

                            GenerateRefDeserializeWithTemp(sb, currentMember, tempName, GetDeserializerVarName, customFormatterVarsByMember);

                            // Assign back
                            if (isPrivate)
                            {
                                var accessName = nt.TypeSymbol.IsValueType ? $"ref {valName}" : valName;
                                sb.AppendLine("#if NET8_0_OR_GREATER");
                                sb.AppendLine($"            PrivateAccessor.__set__{name}__({accessName}, {tempName});");
                                sb.AppendLine("#else");
                                sb.AppendLine($"            {valName}.__nino__generated__{name} = {tempName};");
                                sb.AppendLine("#endif");
                            }
                            else
                            {
                                sb.AppendLine($"            {valName}.{name} = {tempName};");
                            }
                        }
                        else
                        {
                            // Private field
                            sb.AppendLine("#if NET8_0_OR_GREATER");
                            GeneratePrivateFieldDeserialize(sb, currentMember, valName, name, nt, GetDeserializerVarName, customFormatterVarsByMember);
                            sb.AppendLine("#else");
                            GeneratePrivateFieldDeserializeFallback(sb, currentMember, valName, name, tempName, GetDeserializerVarName, customFormatterVarsByMember);
                            sb.AppendLine("#endif");
                        }
                    }
                    else
                    {
                        var readStatement = GenerateReadStatement(currentMember, tempName, GetDeserializerVarName, customFormatterVarsByMember);
                        var toleranceCode = $$$"""
                                                           {{{declaredType.GetDisplayString()}}} {{{tempName}}} = default;
                                                           #if {{{NinoTypeHelper.WeakVersionToleranceSymbol}}}
                                                           if (!reader.Eof)
                                                           {
                                                              {{{readStatement}}}
                                                           }
                                                           #else
                                                           {{{readStatement}}}
                                                           #endif
                                               """;
                        sb.AppendLine(toleranceCode);
                    }
                }
            }
            else
            {
                // Standard path with version tolerance
                sb.AppendLine($"#if {NinoTypeHelper.WeakVersionToleranceSymbol}");
                for (var index = 0; index < valNames.Count; index++)
                {
                    var val = valNames[index];
                    sb.AppendLine($"            {members[index].Type.GetDisplayString()} {val} = default;");
                    sb.AppendLine($"            if (!reader.Eof) reader.Read(out {val});");
                }

                sb.AppendLine("#else");
                sb.AppendLine(
                    $"            reader.Read(out NinoTuple<{string.Join(", ",
                        Enumerable.Range(0, valNames.Count)
                            .Select(i => $"{members[i].Type.GetDisplayString()}"))}> t{index1});");
                for (int i = 0; i < members.Count; i++)
                {
                    var name = members[i].Name;
                    tupleMap[name] = $"t{index1}.Item{i + 1}";
                }

                sb.AppendLine("#endif");
            }
        }

        return (vars, privateVars, args, tupleMap);
    }

    private void WriteMembersWithCustomConstructor(SourceProductionContext spc,
        StringBuilder sb, NinoType nt,
        string valName,
        string[] constructorMember,
        IMethodSymbol? constructor)
    {
        var (vars, privateVars, args, tupleMap) =
            WriteMembers(valName, sb, nt, constructorMember, constructor == null);

        if (constructor != null)
        {
            List<string> ctorArgs = new List<string>();

            string? missingArg = null;
            foreach (var m in constructorMember)
            {
                var k = args.Keys.FirstOrDefault(k =>
                    k.ToLower().Equals(m.ToLower()));
                if (k != null)
                {
                    ctorArgs.Add(k);
                }
                else
                {
                    sb.AppendLine($"            // missing constructor member {m}");
                    missingArg = m;
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("NINO001", "Nino Generator",
                            "Missing constructor member {0} for {1}",
                            "Nino.Generator",
                            DiagnosticSeverity.Error, true), constructor.Locations[0],
                        m, nt.TypeSymbol.GetDisplayString()));
                    break;
                }
            }

            if (missingArg != null)
            {
                sb.AppendLine(
                    $"            throw new InvalidOperationException(\"Missing constructor member {missingArg}\");");
                return;
            }

            var ctorStmt = constructor.MethodKind == MethodKind.Constructor
                ? $"new {nt.TypeSymbol.GetDisplayString()}"
                : $"{nt.TypeSymbol.GetDisplayString()}.{constructor.Name}";
            if (args.Keys.Any(tupleMap.ContainsKey))
            {
                sb.AppendLine($"#if {NinoTypeHelper.WeakVersionToleranceSymbol}");
                sb.AppendLine(
                    $"            {valName} = {ctorStmt}({string.Join(", ", ctorArgs.Select(k => args[k]))}){(vars.Count > 0 ? "" : ";")}");
                sb.AppendLine("#else");
                sb.AppendLine(
                    $"            {valName} = {ctorStmt}({string.Join(", ", ctorArgs.Select(k =>
                    {
                        if (!tupleMap.TryGetValue(k, out var value))
                        {
                            return args[k];
                        }

                        return value;
                    }))}){(vars.Count > 0 ? "" : ";")}");
                sb.AppendLine("#endif");
            }
            else
            {
                sb.AppendLine(
                    $"            {valName} = {ctorStmt}({string.Join(", ", ctorArgs.Select(k => args[k]))}){(vars.Count > 0 ? "" : ";")}");
            }
        }

        char eol = constructor == null ? ';' : ',';
        if (vars.Count > 0)
        {
            string padding = new string(' ', valName.Length);
            sb.AppendLine($"            {padding}   {{");
            foreach (var (memberName, varName) in vars)
            {
                if (tupleMap.TryGetValue(memberName, out var value))
                {
                    var name = constructor == null ? $"{valName}.{memberName}" : memberName;
                    sb.AppendLine($"#if {NinoTypeHelper.WeakVersionToleranceSymbol}");
                    sb.AppendLine(
                        $"            {padding}      \t{name} = {varName}{eol}");
                    sb.AppendLine("#else");
                    sb.AppendLine(
                        $"            {padding}      \t{name} = {value}{eol}");
                    sb.AppendLine("#endif");
                }
                else
                {
                    var name = constructor == null ? $"{valName}.{memberName}" : memberName;
                    sb.AppendLine(
                        $"            {padding}      \t{name} = {varName}{eol}");
                }
            }

            sb.AppendLine($"            {padding}   }};");
        }

        if (privateVars.Count > 0)
        {
            var originalValName = valName;

            if (nt.TypeSymbol.IsValueType)
            {
                valName = $"ref {valName}";
            }

            static void AppendAccess(StringBuilder sb, bool isProperty, string memberName, string valName,
                string varName)
            {
                if (isProperty)
                {
                    sb.AppendLine(
                        $"            PrivateAccessor.__set__{memberName}__({valName}, {varName});");
                }
                else
                {
                    sb.AppendLine(
                        $"            ref var __{varName} = ref PrivateAccessor.__{memberName}__({valName});");
                    sb.AppendLine($"            __{varName} = {varName};");
                }
            }

            sb.AppendLine("#if NET8_0_OR_GREATER");
            foreach (var (memberName, varName, isProperty) in privateVars)
            {
                if (tupleMap.TryGetValue(memberName, out var value))
                {
                    sb.AppendLine($"#if {NinoTypeHelper.WeakVersionToleranceSymbol}");
                    AppendAccess(sb, isProperty, memberName, valName, varName);
                    sb.AppendLine("#else");
                    AppendAccess(sb, isProperty, memberName, valName, value);
                    sb.AppendLine("#endif");
                }
                else
                {
                    AppendAccess(sb, isProperty, memberName, valName, varName);
                }
            }

            sb.AppendLine("#else");
            foreach (var (memberName, varName, _) in privateVars)
            {
                var legacyVal = $"{originalValName}.__nino__generated__{memberName}";
                if (tupleMap.TryGetValue(memberName, out var value))
                {
                    sb.AppendLine($"#if {NinoTypeHelper.WeakVersionToleranceSymbol}");
                    sb.AppendLine($"            {legacyVal} = {varName};");
                    sb.AppendLine("#else");
                    sb.AppendLine($"            {legacyVal} = {value};");
                    sb.AppendLine("#endif");
                }
                else
                {
                    sb.AppendLine($"            {legacyVal} = {varName};");
                }
            }

            sb.AppendLine("#endif");
        }
    }

    private void CreateInstance(SourceProductionContext spc, StringBuilder sb,
        NinoType nt, string valName, bool byRef)
    {
        if (byRef)
        {
            WriteMembersWithCustomConstructor(spc, sb, nt, valName, [], null);
            return;
        }

        //if this subtype contains a custom constructor, use it
        //go through all constructors and find the one with the NinoConstructor attribute
        //get constructors of the symbol
        var constructors = (nt.TypeSymbol as INamedTypeSymbol)?.Constructors.ToList();

        // append static methods that return an instance of the type
        constructors ??= [];
        constructors.AddRange(nt.TypeSymbol.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.DeclaredAccessibility == Accessibility.Public &&
                        m.IsStatic &&
                        SymbolEqualityComparer.Default.Equals(m.ReturnType, nt.TypeSymbol)));

        if (constructors.Count == 0)
        {
            sb.AppendLine(
                $"            // no constructor found, symbol is not a named type symbol but a {nt.TypeSymbol.GetType()}");
            sb.AppendLine(
                $"            throw new InvalidOperationException(\"No constructor found for {nt.TypeSymbol.GetDisplayString()}\");");
            return;
        }

        IMethodSymbol? constructor = null;

        // if typesymbol is a record, try get the primary constructor
        if (nt.TypeSymbol.IsRecord)
        {
            constructor = constructors.FirstOrDefault(c => c.Parameters.Length == 0 || c.Parameters.All(p =>
                nt.Members.Any(m => m.Name == p.Name)));
        }

        if (constructor == null)
            constructor = constructors.OrderBy(c => c.Parameters.Length).FirstOrDefault();

        var custom = constructors.FirstOrDefault(c => c.GetAttributesCache().Any(a =>
            a.AttributeClass != null &&
            a.AttributeClass.GetDisplayString().EndsWith("NinoConstructorAttribute")));
        if (custom != null)
        {
            constructor = custom;
        }

        if (constructor == null)
        {
            sb.AppendLine("            // no constructor found");
            sb.AppendLine(
                $"            throw new InvalidOperationException(\"No constructor found for {nt.TypeSymbol.GetDisplayString()}\");");
            return;
        }

        sb.AppendLine($"            // use {constructor.ToDisplayString()}");

        var attr = constructor.GetNinoConstructorAttribute();
        string[] args;
        if (attr != null)
        {
            //attr is         [NinoConstructor(nameof(a), nameof(b), nameof(c), ...)]
            //we need to get a, b, c, ...
            var args0 = attr.ConstructorArguments[0].Values;
            //should be a string array
            args = args0.Select(a =>
                a.Value as string).ToArray()!;
        }
        else
        {
            args = constructor.Parameters.Select(p => p.Name).ToArray();
        }

        WriteMembersWithCustomConstructor(spc, sb, nt, valName, args, constructor);
    }


    private static string GeneratePrivateDeserializeImplMethodBody(string typeName, string indent = "",
        string typeParam = "",
        string genericConstraint = "")
    {
        var ret = $$"""
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    public static void Deserialize{{typeParam}}(out {{typeName}} value, ref Reader reader) {{genericConstraint}}
                    {
                    #if {{NinoTypeHelper.WeakVersionToleranceSymbol}}
                         if (reader.Eof)
                         {
                            value = default;
                            return;
                         }
                    #endif
                        
                        reader.Read(out value);
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    public static void DeserializeRef{{typeParam}}(ref {{typeName}} value, ref Reader reader) {{genericConstraint}}
                    {
                    #if {{NinoTypeHelper.WeakVersionToleranceSymbol}}
                         if (reader.Eof)
                         {
                            value = default;
                            return;
                         }
                    #endif
                        
                        reader.Read(out value);
                    }
                    """;

        // indent
        ret = ret.Replace("\n", $"\n{indent}");
        return $"{indent}{ret}";
    }

    private Dictionary<string, (ITypeSymbol FormatterType, ITypeSymbol ValueType)> CollectGlobalCustomFormatters()
    {
        var globalCustomFormatters = new Dictionary<string, (ITypeSymbol FormatterType, ITypeSymbol ValueType)>();

        foreach (var ninoType in NinoTypes)
        {
            foreach (var member in ninoType.Members)
            {
                if (member.HasCustomFormatter())
                {
                    var formatterType = member.CustomFormatterType();
                    if (formatterType != null)
                    {
                        var key = $"{formatterType.GetDisplayString()}_{member.Type.GetDisplayString()}";
                        globalCustomFormatters[key] = (formatterType, member.Type);
                    }
                }
            }
        }

        return globalCustomFormatters;
    }

    private string GenerateStaticFormatterFields(
        Dictionary<string, (ITypeSymbol FormatterType, ITypeSymbol ValueType)> globalCustomFormatters)
    {
        if (globalCustomFormatters.Count == 0)
            return "";

        var sb = new StringBuilder();
        sb.AppendLine();
        sb.AppendLine("        // Static formatter fields for optimal performance");

        foreach (var kvp in globalCustomFormatters)
        {
            var formatterType = kvp.Value.FormatterType;
            var valueType = kvp.Value.ValueType;
            var varName = formatterType.GetCachedVariableName("formatter");
            sb.AppendLine(
                $"        private static readonly {formatterType.GetDisplayString()} {varName} = NinoFormatterInstance<{formatterType.GetDisplayString()}, {valueType.GetDisplayString()}>.Instance;");
        }

        return sb.ToString();
    }
}