using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Nino.Generator.Collection;
using Nino.Generator.Metadata;
using Nino.Generator.Template;

namespace Nino.Generator.Common;

public partial class SerializerGenerator(
    Compilation compilation,
    NinoGraph ninoGraph,
    List<NinoType> ninoTypes,
    List<ITypeSymbol> potentialTypes)
    : NinoCommonGenerator(compilation, ninoGraph, ninoTypes)
{
    private void GenerateGenericRegister(StringBuilder sb, string name, HashSet<ITypeSymbol> generatedTypes)
    {
        sb.AppendLine($$"""
                                private static void Register{{name}}Serializers()
                                {
                        """);
        foreach (var type in generatedTypes)
        {
            // no pure unmanaged types
            if (type.IsUnmanagedType)
            {
                if (!NinoGraph.TypeMap.TryGetValue(type, out var nt) || !nt.IsPolymorphic())
                    continue;
            }

            // no ref struct types
            if (type.IsRefStruct())
                continue;
            var typeFullName = type.GetDisplayString();
            sb.AppendLine($$"""
                                        _serializers[typeof({{typeFullName}}).TypeHandle.Value] = (object value, ref Writer writer) =>
                                            {
                                                Serialize(({{typeFullName}})value, ref writer);
                                            };
                            """);
        }

        sb.AppendLine("        }");
    }

    protected override void Generate(SourceProductionContext spc)
    {
        var compilation = Compilation;

        StringBuilder sb = new(32_000_000);
        HashSet<ITypeSymbol> generatedTypes = new(SymbolEqualityComparer.Default);
        GenerateTrivialCode(spc, generatedTypes);
        // add string type
        generatedTypes.Add(compilation.GetSpecialType(SpecialType.System_String));
        GenerateGenericRegister(sb, "Trivial", generatedTypes);

        generatedTypes.Clear();
        new CollectionSerializerGenerator(compilation, potentialTypes).Generate(spc, generatedTypes);
        GenerateGenericRegister(sb, "Collection", generatedTypes);

        var curNamespace = compilation.AssemblyName!.GetNamespace();
        // generate code
        var genericCode = $$"""
                            // <auto-generated/>
                            using System;
                            using global::Nino.Core;
                            using System.Buffers;
                            using System.ComponentModel;
                            using System.Collections.Generic;
                            using System.Collections.Concurrent;
                            using System.Runtime.InteropServices;
                            using System.Runtime.CompilerServices;

                            namespace {{curNamespace}}
                            {
                                public static partial class Serializer
                                {
                                    private delegate void SerializeDelegate(object value, ref Writer writer);
                                    private static Dictionary<IntPtr, SerializeDelegate> _serializers = new();

                                    static Serializer()
                                    {
                                        RegisterTrivialSerializers();
                                        RegisterCollectionSerializers();
                                    }

                                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                    public static byte[] Serialize<T>(this T value)
                                    {
                                        var bufferWriter = GetBufferWriter();
                                        try
                                        {
                                            var writer = new Writer(bufferWriter);
                                            Serialize(value, ref writer);
                                            return bufferWriter.WrittenSpan.ToArray();
                                        }
                                        finally
                                        {
                                            ReturnBufferWriter(bufferWriter);
                                        }
                                    }
                                    
                                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                    public static void Serialize<T>(this T value, IBufferWriter<byte> bufferWriter)
                                    {
                                        Writer writer = new Writer(bufferWriter);
                                        Serialize(value, ref writer);
                                    }

                                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                    private static void Serialize<T>(T value, ref Writer writer)
                                    {
                                        if (_serializers.TryGetValue(typeof(T).TypeHandle.Value, out var serializer))
                                        {
                                            serializer.Invoke(value, ref writer);
                                            return;
                                        }

                                        if(!RuntimeHelpers.IsReferenceOrContainsReferences<T>())
                                        {
                                            writer.Write(value);
                                            return;
                                        }
                                        
                                        throw new Exception($"Serializer not found for type {typeof(T).FullName}");
                                    }

                                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                    public static byte[] Serialize(object value, Type type)
                                    {
                                        var bufferWriter = GetBufferWriter();
                                        try
                                        {
                                            var writer = new Writer(bufferWriter);
                                            Serialize(value, ref writer, type);
                                            return bufferWriter.WrittenSpan.ToArray();
                                        }
                                        finally
                                        {
                                            ReturnBufferWriter(bufferWriter);
                                        }
                                    }
                                    
                                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                    public static void Serialize(object value, IBufferWriter<byte> bufferWriter, Type type)
                                    {
                                        Writer writer = new Writer(bufferWriter);
                                        Serialize(value, ref writer, type);
                                    }

                                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                    private static void Serialize(object value, ref Writer writer, Type type)
                                    {
                                        if (!_serializers.TryGetValue(type.TypeHandle.Value, out var serializer))
                                        {
                                            throw new Exception($"Serializer not found for type {type.FullName}, if this is an unmanaged type, please use Serialize<T>(T value, ref Writer writer) instead.");
                                        }

                                        serializer.Invoke(value, ref writer);
                                    }
                            {{sb}}    }
                            }
                            """;

        spc.AddSource("NinoSerializer.Generic.g.cs", genericCode);
    }
}