using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Nino.Generator.Metadata;

namespace Nino.Generator.Common;

public partial class SerializerGenerator
{
    private void GenerateTrivialCode(SourceProductionContext spc, HashSet<ITypeSymbol> generatedTypes)
    {
        var compilation = Compilation;
        var sb = new StringBuilder();
        sb.GenerateClassSerializeMethods("string");
        HashSet<string> generatedTypeNames = new();

        foreach (var ninoType in NinoTypes)
        {
            try
            {
                if (!generatedTypes.Add(ninoType.TypeSymbol))
                    continue;
                if (!generatedTypeNames.Add(ninoType.TypeSymbol.GetDisplayString()))
                    continue;

                if (!ninoType.TypeSymbol.IsInstanceType() ||
                    !string.IsNullOrEmpty(ninoType.CustomSerializer))
                    continue;
                sb.AppendLine();
                sb.AppendLine($$"""
                                        [MethodImpl(MethodImplOptions.AggressiveInlining)]
                                        public static void SerializeImpl({{ninoType.TypeSymbol.GetTypeFullName()}} value, ref Writer writer)
                                        {
                                """);

                if (!ninoType.TypeSymbol.IsValueType)
                {
                    sb.AppendLine("            if(value == null)");
                    sb.AppendLine("            {");
                    sb.AppendLine("                writer.Write(TypeCollector.Null);");
                    sb.AppendLine("                return;");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }

                // Optimize polymorphic type writing - inline constant when possible
                if (ninoType.IsPolymorphic())
                {
                    sb.AppendLine(
                        $"            writer.Write(NinoTypeConst.{ninoType.TypeSymbol.GetTypeFullName().GetTypeConstName()});");
                }

                // Optimized write path - direct write for unmanaged types
                if (ninoType.TypeSymbol.IsUnmanagedType)
                {
                    sb.AppendLine("            writer.Write(value);");
                }
                else
                {
                    WriteMembers(ninoType, "value", sb);
                }

                sb.AppendLine("        }");
                sb.AppendLine();
            }
            catch (Exception e)
            {
                sb.AppendLine($"/* Error: {e.Message} for type {ninoType.TypeSymbol.GetTypeFullName()}");
                //add stacktrace
                foreach (var line in e.StackTrace.Split('\n'))
                {
                    sb.AppendLine($" * {line}");
                }

                //end error
                sb.AppendLine(" */");
            }
        }

        var curNamespace = compilation.AssemblyName!.GetNamespace();

        // Collect all custom formatters for static field generation
        var globalCustomFormatters = CollectGlobalCustomFormatters();
        var staticFormatterFields = GenerateStaticFormatterFields(globalCustomFormatters);

        // generate code
        var code = $$"""
                     // <auto-generated/>

                     using System;
                     using System.Buffers;
                     using System.Threading;
                     using global::Nino.Core;
                     using System.ComponentModel;
                     using System.Collections.Generic;
                     using System.Collections.Concurrent;
                     using System.Runtime.InteropServices;
                     using System.Runtime.CompilerServices;

                     namespace {{curNamespace}}
                     {
                         public static partial class Serializer
                         {
                             private static readonly ConcurrentQueue<NinoArrayBufferWriter> BufferWriters = new();
                             private static readonly NinoArrayBufferWriter DefaultBufferWriter = new NinoArrayBufferWriter(1024);
                             private static int _defaultUsed;{{staticFormatterFields}}

                             [MethodImpl(MethodImplOptions.AggressiveInlining)]
                             public static NinoArrayBufferWriter GetBufferWriter()
                             {
                                 // Fast path
                                 if (Interlocked.CompareExchange(ref _defaultUsed, 1, 0) == 0)
                                 {
                                     return DefaultBufferWriter;
                                 }

                                 if (BufferWriters.Count == 0)
                                 {
                                     return new NinoArrayBufferWriter(1024);
                                 }

                                 if (BufferWriters.TryDequeue(out var bufferWriter))
                                 {
                                     return bufferWriter;
                                 }

                                 return new NinoArrayBufferWriter(1024);
                             }

                             [MethodImpl(MethodImplOptions.AggressiveInlining)]
                             public static void ReturnBufferWriter(NinoArrayBufferWriter bufferWriter)
                             {
                     #if NET8_0_OR_GREATER
                                 bufferWriter.ResetWrittenCount();
                     #else
                                 bufferWriter.Clear();
                     #endif
                                 // Check if the buffer writer is the default buffer writer
                                 if (bufferWriter == DefaultBufferWriter)
                                 {
                                     // Ensure it is in use, otherwise throw an exception
                                     if (Interlocked.CompareExchange(ref _defaultUsed, 0, 1) == 0)
                                     {
                                         throw new InvalidOperationException("The returned buffer writer is not in use.");
                                     }

                                     return;
                                 }

                                 BufferWriters.Enqueue(bufferWriter);
                             }
                             
                             [MethodImpl(MethodImplOptions.AggressiveInlining)]
                             public static byte[] Serialize(bool value)
                             {
                                 if (value)
                                     return new byte[1] { 1 };
                                
                                 return new byte[1] { 0 };
                             }
                             
                             [MethodImpl(MethodImplOptions.AggressiveInlining)]
                             public static byte[] Serialize(byte value)
                             {
                                 return new byte[1] { value };
                             }

                     {{GenerateWriterAccessMethodBody("string", "        ")}}

                     {{sb}}    }
                     }
                     """;

        spc.AddSource($"{curNamespace}.Serializer.g.cs", code);
    }

    private static string GenerateWriterAccessMethodBody(string typeName, string indent = "",
        string typeParam = "",
        string genericConstraint = "")
    {
        var ret = $$"""
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    public static void Serialize{{typeParam}}({{typeName}} value, ref Writer writer) {{genericConstraint}}
                    {
                        writer.Write(value);
                    }
                    """;

        // indent
        ret = ret.Replace("\n", $"\n{indent}");
        return $"{indent}{ret}";
    }

    private Dictionary<string, (ITypeSymbol FormatterType, ITypeSymbol ValueType)> CollectGlobalCustomFormatters()
    {
        var globalCustomFormatters = new Dictionary<string, (ITypeSymbol FormatterType, ITypeSymbol ValueType)>();
        
        foreach (var ninoType in NinoTypes)
        {
            foreach (var member in ninoType.Members)
            {
                if (member.HasCustomFormatter())
                {
                    var formatterType = member.CustomFormatterType();
                    if (formatterType != null)
                    {
                        var key = $"{formatterType.GetDisplayString()}_{member.Type.GetDisplayString()}";
                        globalCustomFormatters[key] = (formatterType, member.Type);
                    }
                }
            }
        }
        
        return globalCustomFormatters;
    }

    private string GenerateStaticFormatterFields(Dictionary<string, (ITypeSymbol FormatterType, ITypeSymbol ValueType)> globalCustomFormatters)
    {
        if (globalCustomFormatters.Count == 0)
            return "";

        var sb = new StringBuilder();
        sb.AppendLine();
        sb.AppendLine("        // Static formatter fields for optimal performance");
        
        foreach (var kvp in globalCustomFormatters)
        {
            var formatterType = kvp.Value.FormatterType;
            var valueType = kvp.Value.ValueType;
            var varName = formatterType.GetCachedVariableName("formatter");
            sb.AppendLine($"        private static readonly {formatterType.GetDisplayString()} {varName} = NinoFormatterInstance<{formatterType.GetDisplayString()}, {valueType.GetDisplayString()}>.Instance;");
        }
        
        return sb.ToString();
    }

    private void WriteMembers(NinoType type, string valName, StringBuilder sb)
    {
        // First pass: collect all types that need serializers or custom formatters
        HashSet<ITypeSymbol> typesNeedingSerializers = new(SymbolEqualityComparer.Default);
        HashSet<NinoMember> membersWithCustomFormatters = new();
        
        foreach (var members in type.GroupByPrimitivity())
        {
            // Collect types for single-member serialization that use NinoSerializer.Serialize
            if (members.Count == 1)
            {
                var member = members[0];
                if (!(member.Type.SpecialType == SpecialType.System_String && member.IsUtf8String))
                {
                    if (member.HasCustomFormatter())
                    {
                        membersWithCustomFormatters.Add(member);
                    }
                    else if (member.Type.IsUnmanagedType && 
                             (!NinoGraph.TypeMap.TryGetValue(member.Type.GetDisplayString(), out var ninoTypeCheck) ||
                              !ninoTypeCheck.IsPolymorphic()))
                    {
                        // Unmanaged, non-polymorphic types can use writer.Write() directly - no need for serializer
                    }
                    else if (member.Type.SpecialType == SpecialType.System_String)
                    {
                        // String types are handled directly in Priority 3 - no need for serializer
                    }
                    else
                    {
                        typesNeedingSerializers.Add(member.Type);
                    }
                }
            }
        }
        
        // Generate serializer declarations for standard types
        Dictionary<string, string> serializerVarsByType = new();
        foreach (var serializerType in typesNeedingSerializers)
        {
            var typeDisplayName = serializerType.GetDisplayString();
            var varName = serializerType.GetCachedVariableName("serializer");
            
            // Handle potential duplicates by adding a counter
            var originalVarName = varName;
            int counter = 1;
            while (serializerVarsByType.Values.Contains(varName))
            {
                varName = $"{originalVarName}_{counter}";
                counter++;
            }
            
            serializerVarsByType[typeDisplayName] = varName;
            sb.AppendLine($"            var {varName} = CachedSerializer<{typeDisplayName}>.Instance;");
        }
        
        // Use static formatter fields instead of local variables
        Dictionary<NinoMember, string> customFormatterVarsByMember = new();
        foreach (var member in membersWithCustomFormatters)
        {
            var formatterType = member.CustomFormatterType();
            if (formatterType != null)
            {
                var varName = formatterType.GetCachedVariableName("formatter");
                customFormatterVarsByMember[member] = varName;
                // Note: Static field should be generated at class level, not as local variable
            }
        }
        
        // Helper to get serializer variable name for a type
        string GetSerializerVarName(ITypeSymbol serializerType)
        {
            return serializerVarsByType[serializerType.GetDisplayString()];
        }

        List<string> valNames = new();
        foreach (var members in type.GroupByPrimitivity())
        {
            valNames.Clear();
            foreach (var member in members)
            {
                var name = member.Name;
                var isPrivate = member.IsPrivate;
                var isProperty = member.IsProperty;
                var val = $"{valName}.{name}";

                if (isPrivate)
                {
                    var accessName = valName;
                    if (type.TypeSymbol.IsValueType)
                    {
                        accessName = $"ref {valName}";
                    }

                    val = isProperty
                        ? $"PrivateAccessor.__get__{name}__({accessName})"
                        : $"PrivateAccessor.__{name}__({accessName})";
                    var legacyVal = $"{valName}.__nino__generated__{name}";
                    val = $"""

                           #if NET8_0_OR_GREATER
                                                   {val}
                           #else
                                                   {legacyVal}
                           #endif

                           """;
                }

                valNames.Add(val);
            }

            if (members.Count == 1)
            {
                var member = members[0];
                var declaredType = member.Type;
                var val = valNames[0];

                if (member.HasCustomFormatter())
                {
                    // PRIORITY 1: Custom formatter (highest priority)
                    if (customFormatterVarsByMember.TryGetValue(member, out var formatterVar))
                    {
                        sb.AppendLine($"            {formatterVar}.Serialize({val}, ref writer);");
                    }
                }
                else if (declaredType.IsUnmanagedType &&
                         (!NinoGraph.TypeMap.TryGetValue(declaredType.GetDisplayString(), out var ninoTypeCheck) ||
                          !ninoTypeCheck.IsPolymorphic()))
                {
                    // PRIORITY 2: Unmanaged non-polymorphic types - write directly
                    sb.AppendLine($"            writer.Write({val});");
                }
                else if (declaredType.SpecialType == SpecialType.System_String)
                {
                    // PRIORITY 3: String types (UTF8 and UTF16 optimizations)
                    if (member.IsUtf8String)
                    {
                        sb.AppendLine($"            writer.WriteUtf8({val});");
                    }
                    else
                    {
                        sb.AppendLine($"            writer.Write({val});");
                    }
                }
                else if (declaredType.SpecialType == SpecialType.System_Object)
                {
                    // PRIORITY 4: Object type - call boxed API in NinoSerializer directly
                    sb.AppendLine($"            NinoSerializer.SerializeBoxed({val}, ref writer, {val}?.GetType());");
                }
                else
                {
                    // PRIORITY 5: CachedSerializer fallback
                    var serializerVar = GetSerializerVarName(declaredType);
                    sb.AppendLine($"            {serializerVar}.Serialize({val}, ref writer);");
                }
            }
            else
            {
                // Standard path with version tolerance support
                sb.AppendLine($"#if {NinoTypeHelper.WeakVersionToleranceSymbol}");
                foreach (var val in valNames)
                {
                    sb.AppendLine($"            writer.Write({val});");
                }

                sb.AppendLine("#else");
                sb.AppendLine($"            writer.Write(NinoTuple.Create({string.Join(", ", valNames)}));");
                sb.AppendLine("#endif");
            }
        }
    }
}