name: Claude Code Review - Secure Analysis

on:
  workflow_run:
    workflows: ["Claude Code Review - Collect PR Data"]
    types: [completed]

jobs:
  secure-review:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      actions: read

    steps:
      - name: Download and extract PR artifacts
        id: download
        run: |
          # Get artifacts from the workflow run
          ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts)
          ARTIFACT_ID=$(echo "$ARTIFACTS" | jq -r '.artifacts[0].id')
          ARTIFACT_NAME=$(echo "$ARTIFACTS" | jq -r '.artifacts[0].name')

          echo "Downloading artifact: $ARTIFACT_NAME (ID: $ARTIFACT_ID)"

          # Download the artifact
          gh api repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip > artifact.zip

          # Extract it
          unzip -q artifact.zip

          # Read PR info
          if [ -f pr-info.txt ]; then
            echo "=== PR Info ==="
            cat pr-info.txt
            PR_NUM=$(grep "PR Number:" pr-info.txt | cut -d' ' -f3)
            echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT
            echo "Found PR number: $PR_NUM"
          else
            echo "ERROR: pr-info.txt not found"
            exit 1
          fi

          # Check diff file
          if [ -f pr.diff ]; then
            echo "Diff file size: $(wc -l < pr.diff) lines"
          else
            echo "ERROR: pr.diff not found"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ steps.download.outputs.pr_number }}

            A PR diff file has been provided at: pr.diff

            Please review this pull request diff and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.

            IMPORTANT: Do not execute any code from the PR. Only analyze the diff file.
            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh pr comment:*),Bash(gh pr view:*),Bash(cat:pr.diff),Bash(cat:pr-info.txt)"'
